upgraded to use argutil
Signed-off-by: Rahul Jadhav <nyrahul@gmail.com>

diff --git a/knoxcli b/knoxcli
--- a/knoxcli
+++ b/knoxcli
@@ -21,9 +21,9 @@ EOR
 read -r -d '' filecontent <<EOR
 #!/bin/bash
 
-arg_shortopts="h"
-arg_longopts="help "
-declare -A arg_desclist
+arg_shortopts=""
+arg_longopts=" "
+declare -a arg_desclist
 declare -A arg_handlers
 declare -A arg_nvlist
 
@@ -32,6 +32,11 @@ argopt()
 	mand=""
 	arg=""
 	handler="none"
+	sopt=""
+	desc=""
+	lopt=""
+	soptdesc=""
+	optdesc=""
 	OPTS=\$(getopt -o "s:l:d:" --long "needval sopt: lopt: desc: reqarg mandatory handler:" -n 'parse-options' -- "\$@")
     eval set -- "\$OPTS"
     while true; do
@@ -48,9 +53,11 @@ argopt()
         esac
     done
 	[[ "\$lopt" == "" ]] && echo "ERROR(argopt): long option is a mandatory field!" && return 1
-	arg_desclist["\$lopt"]=\$(echo "-\$sopt|--\$lopt \$arg => \$desc. \$mand")
+	[[ "\$sopt" != "" ]] && soptdesc="-\$sopt | "
+	[[ "\$arg" != "" ]] && optdesc="[value] "
+	arg_desclist+=("\$soptdesc--\$lopt \$optdesc=> \$desc. \$mand")
 	arg_handlers["\$lopt"]=\$handler
-	arg_shortopts="\$arg_shortopts\$sopt\$arg"
+	[[ "\$sopt" != "" ]] && arg_shortopts="\$arg_shortopts\$sopt\$arg"
 	arg_longopts="\$arg_longopts\$lopt\$arg "
 	arg_nvlist["\$lopt"]=\$arg
 	return 0
@@ -59,16 +66,26 @@ argopt()
 arghelp()
 {
 	echo "Supported options:"
-	printf '\t%s\n' "\${arg_desclist[@]}"
+	echo ;
+	printf "\t%s\n" "\${arg_desclist[@]}"
 }
 
 arghandle()
 {
 	handler=\${arg_handlers["\$1"]}
 	needval=\${arg_nvlist["\$1"]}
-	[[ "\$needval" == ":" ]] && \$handler "\$2" && return 2
-	\$handler
+	[[ "\$needval" == ":" ]] && \$handler "\$1" "\$2" && return 2
+	\$handler "\$1"
 	return 1
+}
+
+arginit()
+{
+	arg_shortopts=()
+	arg_longopts=()
+	arg_desclist=()
+	arg_handlers=()
+	arg_nvlist=()
 }
 
 argrun()
@@ -79,9 +96,9 @@ argrun()
     eval set -- "\$OPTS"
     while true; do
 		case "\$1" in
-			-h | --help) arghelp; exit 2;;
+			-h | --help) arghandle "help"; return 2;;
 			--) shift; break ;;
-			*) arghandle \${1/--/} \$2; shift \$?;;
+			*) arghandle \${1/--/} "\$2"; shift \$?;;
 		esac
     done
 }
@@ -196,31 +213,6 @@ etime=\$(date +%s)
 alerttype="kubearmor"
 filters=""
 
-cluster_alerts_help()
-{
-	cat <<EOH
-### [cluster alerts] command
-
-Options supported:
-* --clusterjq [jq-spec]: jq filter to be used on cluster list output (default: '\$clusterjq')
-* --alertjq [jq-spec]: jq filter to be used on cluster list output (default: '\$alertjq')
-* --stime [datetime]: start time in epoch format (default: \$stimestr)
-* --etime [datetime]: end time in epoch format (default: now)
-* --type [alert-type]: alert-type (default: "\$alerttype")
-* --filters [filter-spec]: Alert filters to be passed to API (default: '\$filters')
-
-Examples:
-1. knoxcli cluster alerts --alertjq '.response[] | select(.Resource // "unknown" | test("ziggy"))' <br>
-	... list all the alerts containing 'ziggy' in the Resource filter
-2. knoxcli cluster alerts --filters '{"field":"HostName","value":"store54055","op":"match"}' --alertjq '.response[] | "hostname=\(.HostName),resource=\(.Resource//""),UID=\(.UID),operation=\(.Operation)"' <br>
-	... get all alerts for HostName="store54055" and print the response in following csv format hostname,resource,UID,operation
-
-> Difference between --alertjq and --filters? <br>
-> --filters are passed directly to the AccuKnox API. --alertjq operates on the output of the AccuKnox API response. It is recommended to use --filters as far as possible. However, you can use regex/jq based matching criteria with --alertjq.
-
-EOH
-}
-
 cluster_alerts_query()
 {
 	for((pgid=1;;pgid++)); do
@@ -232,29 +224,75 @@ cluster_alerts_query()
 	done
 }
 
+ca_generic_handler()
+{
+	case "\$1" in
+		type ) alerttype="\$2" ;;
+		clusterjq ) clusterjq="\$2" ;;
+		alertjq ) alertjq="\$2" ;;
+		filters ) filters="\$2" ;;
+		stime ) stime="\$2" ;;
+		etime ) etime="\$2" ;;
+		* ) echo "UNKNOWN argopt" ;;
+	esac
+}
+
+ca_help()
+{
+	cat <<EOH
+### [cluster alerts] options
+Show alerts in the context of clusters. These alerts could be from KubeArmor, Network policies, Admission controllers or anything else as reported in "Monitors & Alerts" option in AccuKnox Control Plane.
+
+EOH
+	arghelp
+	cat <<EOH
+Examples:
+
+	1. knoxcli cluster alerts --alertjq '.response[] | select(.Resource // "unknown" | test("ziggy"))'
+		... list all the alerts containing 'ziggy' in the Resource filter
+	2. knoxcli cluster alerts --filters '{"field":"HostName","value":"store54055","op":"match"}' --alertjq '.response[] | "hostname=\(.HostName),resource=\(.Resource//""),UID=\(.UID),operation=\(.Operation)"'
+		... get all alerts for HostName="store54055" and print the response in following csv format hostname,resource,UID,operation
+
+> **Difference between --alertjq and --filters?** <br>
+> --filters are passed directly to the AccuKnox API. --alertjq operates on the output of the AccuKnox API response. It is recommended to use --filters as far as possible. However, you can use regex/jq based matching criteria with --alertjq.
+
+EOH
+}
+
 cluster_alerts_args()
 {
-    OPTS=\`getopt -o f:hs:e: --long "stime: etime: clusterjq: type: filters: alertjq: help" -n 'parse-options' -- "\$@"\`
-    eval set -- "\$OPTS"
-    while true; do
-        case "\$1" in
-            --type)         alerttype="\$2";                shift 2;;
-            --clusterjq)    clusterjq="\$2";                shift 2;;
-            --alertjq)      alertjq="\$2";                  shift 2;;
-            --filters | -f) filters="\$2";                  shift 2;;
-			--stime | -s)   stime=\$(date --date "\$2" +%s); shift 2;;
-			--etime | -e)   etime=\$(date --date "\$2" +%s); shift 2;;
-            -h | --help )   cluster_alerts_help;            exit 2;;
-            -- ) shift; break ;;
-            * ) break ;;
-        esac
-    done
-	[[ \$etime -lt \$stime ]] && echo "etime should be greater than stime" && exit 2
+	arginit
+	argopt 	--lopt "type" --needval --handler "ca_generic_handler" \
+			--desc "set alert type (default: \$alerttype)"
+
+	argopt 	--lopt "clusterjq" --needval --handler "ca_generic_handler" \
+			--desc "jq filter to be used on cluster list output (default: '\$clusterjq')"
+
+	argopt 	--lopt "alertjq" --needval --handler "ca_generic_handler" \
+			--desc "jq filter to be used on cluster list output (default: '\$alertjq')"
+
+	argopt 	--sopt "f" --needval --lopt "filters" --handler "ca_generic_handler" \
+			--desc "Alert filters to be passed to API (default: '\$filters')"
+
+	argopt 	--sopt "s" --needval --lopt "stime" --handler "ca_generic_handler" \
+			--desc "start time in epoch format (default: \$stimestr)"
+
+	argopt 	--sopt "e" --needval --lopt "etime" --handler "ca_generic_handler" \
+			--desc "end time in epoch format (default: now)"
+
+	argopt 	--sopt "h" --lopt "help" --handler "ca_help" \
+			--desc "help with the options"
+
+	argrun "\$@"
+	[[ \$? -ne 0 ]] && return 1
+	[[ \$etime -lt \$stime ]] && echo "etime should be greater than stime" && return 2
+	return 0
 }
 
 cluster_alerts_cmd()
 {
 	cluster_alerts_args "\$@"
+	[[ \$? -ne 0 ]] && return 1
 	ak_api "\$CWPP_URL/cluster-onboarding/api/v1/get-onboarded-clusters?wsid=\$TENANT_ID"
 	final_json=\$(echo \$json_string | jq -r "\$clusterjq")
 	cidlist=""
@@ -275,24 +313,6 @@ clusterjq='.[] | "id=\(.ID),name=\(.ClusterName),status=\(.Status)"'
 nodejq='.result[].NodeName'
 show_nodes=0
 
-cluster_list_help()
-{
-	cat <<EOH
-### [cluster list] command
-* --nodes | -n: lists nodes from the clusters
-* --clusterjq: jq filter to be used on cluster list output (default: '\$clusterjq')
-* --nodejq: jq filter to be used on node list output (default: '\$nodejq')
-
-Examples:
-
-1. knoxcli cluster list --clusterjq '.[] | select(.ClusterName|test("idt."))' --nodes <br>
-	... list all the clusters with idt substring in its names and list all the nodes in those clusters
-2. knoxcli cluster list --clusterjq '.[] | select((.type == "vm") and (.Status == "Inactive")) | "id=\(.ID),name=\(.ClusterName),status=\(.Status)"' <br>
-	... list all the Inactive VM clusters and print their ID,name,status
-
-EOH
-}
-
 cluster_list_get_node_list()
 {
 	echo "List of nodes in cluster [\$cname]:"
@@ -301,21 +321,55 @@ cluster_list_get_node_list()
 	echo \$json_string | jq -r "\$nodejq"
 }
 
+cl_generic_handler()
+{
+	echo "[\$1] ==> [\$2]"
+	case "\$1" in
+		"nodejq" ) nodejq="\$2" ;;
+		"clusterjq" ) clusterjq="\$2" ;;
+		"nodes" ) show_nodes=1 ;;
+		*) echo "UNHANDLER argopt";;
+	esac
+}
+
+cl_help()
+{
+	cat <<EOH
+### [cluster list] options
+List the cluster and corresponding nodes or any other entities (namespaces, workloads) as part of the cluster.
+
+EOH
+	arghelp
+	cat <<EOH
+
+Examples:
+
+	1. knoxcli cluster list --clusterjq '.[] | select(.ClusterName|test("idt."))' --nodes
+		... list all the clusters with idt substring in its names and list all the nodes in those clusters
+	2. knoxcli cluster list --clusterjq '.[] | select((.type == "vm") and (.Status == "Inactive")) | "id=\(.ID),name=\(.ClusterName),status=\(.Status)"'
+		... list all the Inactive VM clusters and print their ID,name,status
+
+EOH
+}
+
 cluster_list_cmd()
 {
-    # Remember to specify : in cases where argument is nessary both in short and long options
-    OPTS=\`getopt -o hn --long "nodes clusterjq: nodejq: help" -n 'parse-options' -- "\$@"\`
-    eval set -- "\$OPTS"
-    while true; do
-        case "\$1" in
-            -n | --nodes ) show_nodes=1;              shift 1;;
-            --nodejq )     nodejq="\$2"; show_nodes=1; shift 2;;
-            --clusterjq)   clusterjq="\$2";            shift 2;;
-            -h | --help )  cluster_list_help;          exit 2;;
-            -- ) shift; break ;;
-            * ) break ;;
-        esac
-    done
+	arginit
+	argopt 	--lopt "clusterjq" --needval --handler "cl_generic_handler" \
+			--desc "jq filter to be used on cluster list output (default: '\$clusterjq')"
+
+	argopt 	--lopt "nodejq" --needval --handler "cl_generic_handler" \
+			--desc "jq filter to be used on node list output (default: '\$nodejq')"
+
+	argopt	--sopt "n" --lopt "nodes" --handler "cl_generic_handler" \
+			--desc "lists nodes from the clusters"
+
+	argopt	--sopt "h" --lopt "help" --handler "cl_help" \
+			--desc "help for cluster list"
+
+	argrun "\$@"
+	[[ \$? -ne 0 ]] && return 1
+
 	echo "List of clusters:"
 	ak_api "\$CWPP_URL/cluster-onboarding/api/v1/get-onboarded-clusters?wsid=\$TENANT_ID"
 	echo \$json_string | jq -r "\$clusterjq"
@@ -335,25 +389,6 @@ clusterjq='.[]'
 policyjq='.'
 polout="policydump"
 operation="list"
-
-cluster_policy_help()
-{
-	cat <<EOH
-### [cluster policy] command
-* --operation [list | dump]: Dump the policies in --dumpdir folder or list the policies
-* --dumpdir | -d: Policy dump directory
-* --clusterjq: jq filter to be used on cluster list output (default: '\$clusterjq')
-* --policyjq: jq filter to be used on policy list output (default: '\$policyjq')
-
-Examples:
-
-1. knoxcli cluster policy --clusterjq '.[] | select(.ClusterName|test("gke"))' --policyjq '.list_of_policies[] | select(.name|test("crypto"))' <br>
-	... get all the policies have 'crypto' in their name for all the clusters having 'gke' in their name
-
-2. knoxcli cluster policy --clusterjq '.[] | select(.ClusterName|test("gke"))' --policyjq '.list_of_policies[] | select(.namespace_name // "notpresent"|test("agents"))' <br>
-	... get all the policies in namespace agents ... if no namespace is present then "notpresent" is substituted.
-EOH
-}
 
 cluster_policy_dump_policy_file()
 {
@@ -389,23 +424,61 @@ cluster_policy_get_policy_list()
 	done
 }
 
+cp_help()
+{
+	cat <<EOH
+### [cluster policy] options
+Enlist the cluster policies. These include all policies, including, KubeArmor, Network, Admission Controller policies.
+
+EOH
+	arghelp
+	cat <<EOH
+Examples:
+
+	1. knoxcli cluster policy --clusterjq '.[] | select(.ClusterName|test("gke"))' --policyjq '.list_of_policies[] | select(.name|test("crypto"))'
+		... get all the policies have 'crypto' in their name for all the clusters having 'gke' in their name
+	2. knoxcli cluster policy --clusterjq '.[] | select(.ClusterName|test("gke"))' --policyjq '.list_of_policies[] | select(.namespace_name // "notpresent"|test("agents"))'
+		... get all the policies in namespace agents ... if no namespace is present then "notpresent" is substituted.
+
+EOH
+}
+
+cp_generic_handler()
+{
+	case "\$1" in
+		operation)    operation="\$2";                shift 2;;
+		clusterjq)    clusterjq="\$2";                shift 2;;
+		policyjq)     policyjq="\$2";                 shift 2;;
+		dumpdir) polout="\$2"; operation="dump"; shift 2;;
+		help )  cp_help; return 2;;
+		* ) echo "UNKNOWN OPT" ;;
+	esac
+}
+
+
 cluster_policy_cmd()
 {
-    # Remember to specify : in cases where argument is nessary both in short and long options
-    OPTS=\`getopt -o d:h --long "operation: policyjq: dumpdir: clusterjq: help" -n 'parse-options' -- "\$@"\`
-    eval set -- "\$OPTS"
-    while true; do
-        case "\$1" in
-            --operation)    operation="\$2";                shift 2;;
-            --clusterjq)    clusterjq="\$2";                shift 2;;
-            --policyjq)     policyjq="\$2";                 shift 2;;
-            -d | --dumpdir) polout="\$2"; operation="dump"; shift 2;;
-            -h | --help )  cluster_policy_help; return;    shift 1;;
-            -- ) shift; break ;;
-            * ) break ;;
-        esac
-    done
-	[[ "\$operation" != "list" ]] && [[ "\$operation" != "dump" ]] && echo "invalid operation [\$operation]!" && return
+	arginit
+	argopt  --lopt "operation" --needval --handler "cp_generic_handler" \
+			--desc "[list|dump] Dump the policies in folder or list the policies. default:\$operation"
+
+	argopt  --lopt "clusterjq" --needval --handler "cp_generic_handler" \
+			--desc "jq filter to be used on cluster list output (default: '\$clusterjq')"
+
+	argopt  --lopt "policyjq" --needval --handler "cp_generic_handler" \
+			--desc "jq filter to be used on policy list output (default: '\$policyjq')"
+
+	argopt  --sopt "d" --lopt "dumpdir" --needval --handler "cp_generic_handler" \
+			--desc "Policy dump directory"
+
+	argopt 	--sopt "h" --lopt "help" --handler "cp_help" \
+			--desc "help with the options"
+
+	argrun "\$@"
+	[[ \$? -ne 0 ]] && return 1
+	[[ "\$operation" != "list" ]] && [[ "\$operation" != "dump" ]] && \
+		echo "invalid operation [\$operation]!" && return 1
+
 	ak_api "\$CWPP_URL/cluster-onboarding/api/v1/get-onboarded-clusters?wsid=\$TENANT_ID"
 	filter_json=\$(echo \$json_string | jq -r "\$clusterjq")
 	while read cline; do
@@ -561,12 +634,12 @@ case "$cmd" in
 		echo -en "\thelp\n"
 		echo "\`\`\`"
 
-		cluster_help
-		cluster_alerts_help
-		cluster_list_help
-		cluster_policy_help
-		image_help
-		image_list_help
-		image_scan_help
+		cluster_cmd --help
+		cluster_alerts_cmd --help
+		cluster_list_cmd --help
+		cluster_policy_cmd --help
+		image_cmd --help
+		image_list_cmd --help
+		image_scan_cmd --help
 		;;
 esac
